import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import {
  faArrowLeft,
  faBug,
  faChartLine,
  faCheck,
  faCheckCircle,
  faChevronRight,
  faCircleXmark,
  faClipboardList,
  faCreditCard,
  faEdit,
  faExclamationCircle,
  faEye,
  faHome,
  faHouse,
  faMinus,
  faMobileAlt,
  faMoneyBillWave,
  faPlus,
  faRedo,
  faSave,
  faShoppingCart,
  faSignInAlt,
  faSignOutAlt,
  faSpinner,
  faTimes,
  faTrash,
  faTrashAlt,
  faUniversity,
  faUserCircle,
  faUserPlus,
  faWallet,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faArrowLeft,
  faBug,
  faChartLine,
  faCheck,
  faCheckCircle,
  faChevronRight,
  faCircleXmark,
  faClipboardList,
  faCreditCard,
  faEdit,
  faExclamationCircle,
  faEye,
  faHome,
  faHouse,
  faMinus,
  faMobileAlt,
  faMoneyBillWave,
  faPlus,
  faRedo,
  faSave,
  faShoppingCart,
  faSignInAlt,
  faSignOutAlt,
  faSpinner,
  faTimes,
  faTrash,
  faTrashAlt,
  faUniversity,
  faUserCircle,
  faUserPlus,
  faWallet,
);

export { FontAwesomeIcon };
